const fs = require('fs');
const bundle = fs.readFileSync('src/bundle/index-Bfvfzxe5.js', 'utf8');

const oldCode = `b=C=>{const T=parseFloat(C.target.value);!isNaN(T)&&T>=0&&(h.current=T,u(T))},E=C=>{const T=parseFloat(C.currentTarget.value),H=!isNaN(T)&&T>=0?T:h.current;t(H),o(!1)};return a.jsxs("div",{className:"w-full flex items-center gap-2 sm:gap-2.5 text-xs font-medium text-neutral-400 select-none",children:[a.jsx("span",{className:"w-8 sm:w-9 text-right text-[11px] font-mono text-neutral-400 select-none tabular-nums flex-shrink-0",children:m(g)}),a.jsxs("div",{className:"relative flex-1 flex items-center h-4 group cursor-pointer select-none py-1",children:[a.jsx("div",{className:"absolute inset-x-0 h-1 bg-white/20 rounded-full group-hover:h-1.5 transition-all overflow-hidden",children:a.jsx("div",{className:"h-full bg-white group-hover:bg-emerald-500 rounded-full transition-[transform] duration-75 ease-out",style:{transform:\`scaleX(\${Math.min(100,Math.max(0,x))/100})\`,transformOrigin:"left"}})}),a.jsx("div",{className:"absolute w-3 h-3 bg-white rounded-full shadow-md -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none",style:{left:\`\${Math.min(100,Math.max(0,x))}%\`}}),a.jsx("input",{id:"miniplayer-seek-slider",type:"range",min:0,max:p,step:.1,value:Math.min(p,Math.max(0,typeof g=="number"&&!Number.isNaN(g)?g:0)),onPointerDown:v,onChange:b,onPointerUp:E,onPointerCancel:E,onPointerLeave:C=>{s&&E(C)},`;

const newCode = `b=C=>{const T=parseFloat(C.target.value);!isNaN(T)&&T>=0&&(h.current=T,u(T),t(T))},E=C=>{const T=parseFloat(C.currentTarget.value),H=!isNaN(T)&&T>=0?T:h.current;t(H),o(!1)};return a.jsxs("div",{className:"w-full flex items-center gap-2 sm:gap-2.5 text-xs font-medium text-neutral-400 select-none",children:[a.jsx("span",{className:"w-8 sm:w-9 text-right text-[11px] font-mono text-neutral-400 select-none tabular-nums flex-shrink-0",children:m(g)}),a.jsxs("div",{className:"relative flex-1 flex items-center h-4 group cursor-pointer select-none py-1",children:[a.jsx("div",{className:"absolute inset-x-0 h-1 bg-white/20 rounded-full group-hover:h-1.5 transition-all overflow-hidden",children:a.jsx("div",{className:"h-full bg-white group-hover:bg-emerald-500 rounded-full transition-[transform] duration-75 ease-out",style:{transform:\`scaleX(\${Math.min(100,Math.max(0,x))/100})\`,transformOrigin:"left"}})}),a.jsx("div",{className:"absolute w-3 h-3 bg-white rounded-full shadow-md -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none",style:{left:\`\${Math.min(100,Math.max(0,x))}%\`}}),a.jsx("input",{id:"miniplayer-seek-slider",type:"range",min:0,max:p,step:.1,value:Math.min(p,Math.max(0,typeof g=="number"&&!Number.isNaN(g)?g:0)),onPointerDown:v,onChange:b,onPointerUp:E,onPointerCancel:E,`;

if (bundle.includes(oldCode)) {
  fs.writeFileSync('src/bundle/index-Bfvfzxe5.js', bundle.replace(oldCode, newCode));
  console.log("Patched miniplayer!");
} else {
  console.log("Miniplayer seek not found! Let's check differences.");
}
